all:
	Rscript -e "library(rmarkdown); rmarkdown::render('lesson1_1.Rmd')"
	Rscript -e "library(rmarkdown); rmarkdown::render('lesson1_2.Rmd')"
	Rscript -e "library(rmarkdown); rmarkdown::render('lesson1_3.Rmd')"
clean:
	rm -rf *.html
