-----

# prew_mort

This dataset was obtained from [the webpage of the textbook: 'Veterinary
Epidemiologic Research'](http://www.upei.ca/ver/datasets-programs). The
description of the dataset is taken from page 828 of the same
textbook.

|Contributor      |Study type     |# records|Unit of record|
|:---------------:|:-------------:|:-------:|:------------:|
|Jette Christensen|cross-sectional|  6552   |    litter    |

## Reference

Christensen J, Svensmark B. Evaluation of producer-recorded causes of
preweaning mortality in Danish sow herds Prev Vet Med. 1997; 32:
155-64.

## Brief description

These data are a subset of 16 herds from a dataset collected by Jette
Christensen in Denmark to study factors affecting preweaning mortality
in pigs. These data have three levels in the hierarchy
(litters(n=6552) within sows (n=3162) within farms(n=16)):

The key outcome of interest is preweaning mortality with a litter
classified as having preweaning mortality or not if one or more
piglets died before weaning.

## Table of variables

| Variable   | Description                                               | Codes/units                                         |
|------------|-----------------------------------------------------------|-----------------------------------------------------|
| herd       | unique herd id                                            |                                                     |
| sowid      | unique sow id                                             |                                                     |
| litter     | unique litter id                                          |                                                     |
| lmort      | prewmort in litter                                        | 0/1                                                 |
| herdtype   | herd type                                                 | 0 = production; 1 = breeding herd                   |
| year       |                                                           |                                                     |
| month      | month                                                     | jan = 1; dec = 12                                   |
| quarter    | quarter of the year                                       | 1 = jan-mar; 2 = apr-jun; 3 = jul-sept; 4 = oct-dec |
| sow_parity | parity of the sow                                         |                                                     |
| sow_tx     | sow required treatment (2d before to 7 d after farrowing) | 0/1                                                 |
| dead       | number of dead piglets in litter                          |                                                     |
| lsize      | litter size                                               |                                                     |
| n          | number at risk in the litter                              |                                                     |
| stillb     | number stillborn                                          |                                                     |

-----

# pig_adg

This dataset was obtained from [the webpage of the textbook: 'Veterinary
Epidemiologic Research'](http://www.upei.ca/ver/datasets-programs). The
description of the dataset is taken from page 828 of the same
textbook.

|Contributor      |Study type     |# records|Unit of record|
|:---------------:|:-------------:|:-------:|:------------:|
|Theresa Bernardo |cross-sectional|  341    |    pig       |

## Reference

Bernardo TM, Dohoo IR, Donald A. Effect of ascariasis and respiratory
deiseases on growth rates in swine. Can J Vet Res; 54: 278-84

## Brief description

These are data on the growth performance and abattoir findings of pigs
from a selection of Price Edward Island, Canada farms. The data were
collected to study the inter-relationships among respiratory
disease(atrophic rhinitis and enzootic pneumonia), ascarid levels and
daily weight gain. Atrophic rhinitis score was determined by splitting
the snout and measuring the space ventral to the turbinates. An
adjustment to the score was made if the nasal septum was
deviated. Lung scores were recorded on a scale of 0 to 3 (negative to
severe pneumonia) and then converted to either the presence or absence
of pneumonia. Parasite burdens were evaluated using fecal egg counts,
counts of adult worms in the intestine and visual assessment of the
liver for ascarid tracks. Production data were recorded by monitoring
the pigs on the farms of origin from birth through to slaughter.

## Table of variables

| Variable | Description                                                              | Codes/units                                      |
|----------+--------------------------------------------------------------------------+--------------------------------------------------|
| farm     | farm identification number                                               |                                                  |
| pig      | pig identification number                                                |                                                  |
| sex      | sex of the pig                                                           | 0 = female; 1 = castrate                         |
| dtm      | days to market (ie from birth to slaughter)                              | days                                             |
| adg      | average daily weight gain                                                | gm                                               |
| mm       | measurement of snout space                                               | mm                                               |
| ar       | atrophic rhinitis score                                                  | 0-5                                              |
| lu       | lung score for enzootic pneumonia                                        | 0 = negative; 1 = mild, 2 = moderate; 3 = severe |
| pn       | pneumonia (lu>0)                                                         | 0/1                                              |
| epg5     | fecal gastrointestinal nematodes in small intestine at time of slaughter | eggs/5 gm                                        |
| worms    | count of nematodes in small intestine at time of slaughter               |                                                  |
| li       | liver score (based on number of parasite induced 'white spots')          | 0 = negative; 1 = mild, 2 = severe               |
| ar2      | severe atrophic rhinitis (ar>4)                                          | 0/1                                              |

