---
output:
    html_document:
        css: style.css
---

[Back to the README](README.html)

---

# Introduction to R

### Day 1

09:00 - 10:30 (1.5h)

* 1 Introduction to R and the RStudio editor
    * 1.1 [Make sure everyone has the correct software](day1/lesson1/lesson1_1.html)
    * 1.2 [How to enter commands in R](day1/lesson1/lesson1_2.html)
    * 1.3 [Comparison of an R-script and a do-file](day1/lesson1/lesson1_3.html)
* 2 Open an existing dataset in R
    * 2.1 [Data from Excel, Stata, and text](day1/lesson2/lesson2_1.html)
* 3 Data structure in R
    * 3.1 [What is a dataframe?](day1/lesson3/lesson3_1.html)
    * 3.2 [What types of data can you store?](day1/lesson3/lesson3_2.html)
* 4 Introduction to exploring and managing your data in R
    * 4.1 [Summarize](day1/lesson4/lesson4_1.html)
	* 4.2 [Tabulate](day1/lesson4/lesson4_2.html)
	* 4.3 [Subsetting](day1/lesson4/lesson4_3.html)

10:30 - 11:00 Coffee and snack provided

11:00 - 12:00 (1.0h)

* 5 Continue with exploring and managing your data in R
	* 5.1 [Generating new variables](day1/lesson5/lesson5_1.html)
	* 5.2 [Appending](day1/lesson5/lesson5_2.html)
	* 5.3 [Merging](day1/lesson5/lesson5_3.html)

12:00 - 13:00 Lunch provided

13:00 - 15:00 (2.0h)

* 6 Analysis of data in R:
	* 6.1
      [Work through examples from Veterinary Epidemiologic Research in R.](day1/lesson6/lesson6_1.html)

15:00 - 15:30 Coffee and snacks provided

15:30 - 17:00 (1.5h)

* 7 Introduction to visualization in R
    * 7.1 [How to plot your data](day1/lesson7/lesson7_1.html)
* 8 Demonstration of interactive and dynamic plotting and mapping in R
    * 8.1 [DataTables](day1/lesson8/lesson8_1.html)
    * 8.2 [TBD](day1/lesson8/lesson8_2.html)
    * 8.3 [TBD](day1/lesson8/lesson8_3.html)

### Day 2

09:00 - 10:30 (1.5h)

* 9 [How to find and read R documentation](day2/lesson9/lesson9_1.html)
* 10 R Extensions
    * 10.1 [How to find and use R extensions \(packages\)](day2/lesson10/lesson10_1.html)
    * 10.2 [Demonstration of packages for veterinary epidemiology](day2/lesson10/lesson10_2.html)
* 11 [Install a package](day2/lesson11/lesson11_1.html)

10:30 - 11:00 Coffee and snacks provided

11:00 - 12:00 (1.0h)

* 12 Plotting continued:
	* 12.1 [Plotting using the popular ggplot2 package](day2/lesson12/lesson12_1.html)

12:00 - 13:00 Lunch provided

13:00 - 15:00 (2.0h)

* 13 Communicate you findings with R
    * 13.1 [Create a report with your analysis results, figures and your
      interpretation in publication quality layout.](day2/lesson13/lesson13_1.html)

15:00 - 15:30 Coffee and snacks provided

15:30 - 17:00 (1.5h)

* 14 [Where to find resources for your next step in learning to use R](day2/lesson14/lesson14_1.html)
* 15 [Wrap up and question and answer period](day2/lesson15/lesson15_1.html)
* 16 [Demonstration of importing and analyzing sequence data](day2/lesson16/lesson16_1.html)
