all:

	Rscript -e "library(rmarkdown); rmarkdown::render('lesson4_1.Rmd')"
	Rscript -e "library(rmarkdown); rmarkdown::render('lesson4_2.Rmd')"
	Rscript -e "library(rmarkdown); rmarkdown::render('lesson4_3.Rmd')"

clean:
	rm -rf *.html
